In [34]:
from sklearn.datasets import load_diabetes

import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split

In [35]:
X, y = load_diabetes(return_X_y=True)

In [36]:
print(X.shape)
print(y.shape)

(442, 10)
(442,)


In [37]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42) 

In [38]:
lr = LinearRegression()
lr.fit(X_train, y_train)

LinearRegression()

In [39]:
lr.coef_

array([  37.90402135, -241.96436231,  542.42875852,  347.70384391,
       -931.48884588,  518.06227698,  163.41998299,  275.31790158,
        736.1988589 ,   48.67065743])

In [40]:
lr.intercept_

151.34560453985995

In [41]:
y_pred = lr.predict(X_test)
r2_score(y_test,y_pred)

0.4526027629719195

In [42]:
import numpy as np
import random

class MBGDRegressor:

    def __init__(self, batch_size, learning_rate=0.01, epochs=100):
        self.coef_ = None
        self.intercept_ = None
        self.lr = learning_rate
        self.epochs = epochs
        self.batch_size = batch_size

    def fit(self, X_train, y_train):

        # Initialize parameters
        self.intercept_ = 0
        self.coef_ = np.ones(X_train.shape[1])

        n = X_train.shape[0]

        for epoch in range(self.epochs):
            
            for _ in range(n // self.batch_size):

                # Mini batch selection
                idx = random.sample(range(n), self.batch_size)

                X_batch = X_train[idx]
                y_batch = y_train[idx]

                # Prediction
                y_hat = np.dot(X_batch, self.coef_) + self.intercept_

                # Error
                error = y_batch - y_hat

                # Intercept gradient
                intercept_der = -2 * np.mean(error)
                # Coefficient gradient
                coef_der = -2 * np.dot(X_batch.T, error) / self.batch_size
                
                # Update
                self.intercept_ -= self.lr * intercept_der
                self.coef_ -= self.lr * coef_der

        print("Final intercept:", self.intercept_)
        print("Final coefficients:", self.coef_)

    def predict(self, X_test):
        return np.dot(X_test, self.coef_) + self.intercept_

In [43]:
mbr = MBGDRegressor(batch_size=int(X_train.shape[0]/50),learning_rate=0.01,epochs=100)

In [44]:
mbr.fit(X_train,y_train)

151.33400327387758 [  44.58584864 -166.84281561  466.8317088   309.21144918  -56.57365579
  -95.8653113  -215.85942791  141.49721472  342.38081653  132.1970246 ]


In [45]:
y_pred = mbr.predict(X_test)

In [46]:
r2_score(y_test,y_pred)

0.45703590671797556

In [47]:
from sklearn.linear_model import SGDRegressor

In [48]:
sgd = SGDRegressor(learning_rate='constant',eta0=0.1)

In [49]:
batch_size = 35

for i in range(100):
    
    idx = random.sample(range(X_train.shape[0]),batch_size)
    sgd.partial_fit(X_train[idx],y_train[idx])

In [50]:
sgd.coef_

array([  65.67058494,  -82.28855971,  358.36700828,  264.33463964,
         15.5628423 ,  -20.93320455, -177.31654777,  155.33338478,
        287.63830926,  139.73256862])

In [51]:
sgd.intercept_

array([153.82026496])

In [52]:
y_pred = sgd.predict(X_test)

In [53]:
r2_score(y_test,y_pred)


0.4448066938073242